/** @format */

import HeaderNavbar from "../../components/HeaderNavbar";
import Provider from "./Provider";
import "./globals.css";
import { Raleway } from "next/font/google";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
	title: "Navigate Nexus",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Provider>
					<HeaderNavbar />
					{children}
				</Provider>
			</body>
		</html>
	);
}
